name: Install Terraform
on: [workflow_dispatch]

jobs:
  install-terraform:
     runs-on: ubuntu-latest  
     steps:
      - name: Install Terraform version 1.1.7
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7" 
        #  terraform_version: ${{inputs.tf-version}}

      - name: check terrform version
        run: |
           terraform -version
           pwd
        
        
