name: read file from directory
on: 
   workflow_dispatch:
   

jobs:
  Read-File:
     runs-on: ubuntu-latest 
     steps:
     - name: checkout
       uses: actions/checkout@v2
       
     - name: read file
     #  shell: pwsh
     #  working-directory: dev
       run: |
          echo pwd
         # ./dev/cat resource-group.tf
  
