name: read file from directory
on: 
   workflow_dispatch:
   

jobs:
  Read-File:
     runs-on: ubuntu-latest 
     steps:
     - name: checkout
       uses: actions/checkout@v2
       
     - name: read file
     #  shell: pwsh
     #  working-directory: dev
       run: |
          echo pwd
          pwd
          ls
          ls -al
          cat readFile.yml
      #    cat ./dev/resource-group.tf

     - name: read file2
       working-directory: dev
       run: |
         pwd
         ls -al

     - name: read file3
       working-directory: dev
       run: |
         pwd
         ls -al
         cat resource-groups.tf

     - name: read file4
       shell: pwsh
       working-directory: dev
       run: |
         pwd
         ls -al
         cat resource-groups.tf
      
  
