name: Secrets usage
on:
  workflow_dispatch:

jobs:
  My-jobs:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - name: set the secret as input and retrieve this secret
        env:
           GREETING: HELLO
           FIRST_NAME: SHANKER
        #  super_secret: ${{ secrets.SUPERSECRET }}
      
        run: |
          echo $GREETING $FIRST_NAME
