name: Secrets usage
on:
  workflow_dispatch:
    inputs:
       subscription:
         description: Subscription
         required: true
         type: string

jobs:
  Myjobs:
    name: Greeting
    runs-on: ubuntu-latest
    steps:
      - name: set the secret as input and retrieve this secret
      
        env:
           GREETING: HELLO
           FIRST_NAME: SHANKER
        #  super_secret: ${{ secrets.SUPERSECRET }}
           SUBNAME: ${{ inputs.subscription }}
      
        run: |
          echo $GREETING $FIRST_NAME
          echo: $SUBNAME
        

        

      

    

        
