on:
  workflow_dispatch:

jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: set the secret as input
        env:
           GREETING: HELLO
           FIRST_NAME: SHANKER
        #  super_secret: ${{ secrets.SUPERSECRET }}
      - name: Retrieve secret
        run: |
          echo $ GREETING $FIRST_NAME
